#!/bin/sh

# Licensed under the Mozilla Public License Version 2.0
# Fedora-License-Identifier: MPLv2.0
# SPDX-2.0-License-Identifier: MPL-2.0
# SPDX-3.0-License-Identifier: MPL-2.0
#
# This is free software.
# For more information on the license, see LICENSE.
# For more information on free software,
# see <https://www.gnu.org/philosophy/free-sw.en.html>.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at <https://mozilla.org/MPL/2.0/>.


RUN_SCRIPT=$(mktemp --suffix="-wl-magpiewm-firstboot-run")

cat > ${RUN_SCRIPT} << EOF
#!/bin/sh
exec $@
EOF

magpie-wm --kiosk "$RUN_SCRIPT"
